# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180513_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nic_kname',
            new_name='nick_name',
        ),
    ]
