# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180601_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.TextField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
