# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180602_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(max_length=10, verbose_name='价格'),
        ),
    ]
